// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package Absyn;

public class ColumnDefList extends List {

  public ColumnDef head;
  public ColumnDefList tail;

  public ColumnDefList (int pos, ColumnDef head, ColumnDefList tail) {
    this.pos = pos;
    this.head = head;
    this.tail = tail;
  }

  public String print(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("ColumnDefList(\n");
      if (head != null)
        buffer.append(head.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (tail != null)
        buffer.append(tail.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [ColumnDefList]");
    return buffer.toString();
  }
}
