// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package Absyn;

public class OrderExp extends Absyn {

  public OrderColumnList list;

  public OrderExp (int pos, OrderColumnList list) {
    this.list = list;
    this.pos = pos;
  }

  public String print(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("OrderExp(\n");
      if (list != null)
        buffer.append(list.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [OrderExp]");
    return buffer.toString();
  }
}
