// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package Absyn;

public class IdList extends List {

  public String head;
  public IdList tail;

  public IdList (int pos, String head, IdList tail) {
    this.head = head;
    this.tail = tail;
    this.pos = pos;
  }

  public String print(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("IdList(\n");
    buffer.append("  "+tab+head);
    buffer.append("\n");
      if (tail != null)
        buffer.append(tail.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [IdList]");
    return buffer.toString();
  }
}
