// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package Absyn;

public class OrderColumn extends Item {

  public boolean isAsc;
  public Column column;

  public OrderColumn (int pos, boolean isAsc, Column column) {
    this.isAsc = isAsc;
    this.column = column;
    this.pos = pos;
  }

  public String print(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("OrderColumn(\n");
    buffer.append("  "+tab+isAsc);
    buffer.append("\n");
      if (column != null)
        buffer.append(column.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [OrderColumn]");
    return buffer.toString();
  }
}
