// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package QueryManager.Parser.Absyn;

public class ColumnCons extends Absyn {

  public int type;
  public ValueExp value;

  public ColumnCons (int pos, int type, ValueExp value) {
    this.pos = pos;
	this.type = type;
    this.value = value;
  }

  public String print(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("ColumnCons(\n");
    buffer.append("  "+tab+type);
    buffer.append("\n");
      if (value != null)
        buffer.append(value.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [ColumnCons]");
    return buffer.toString();
  }
}
