// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package QueryManager.Parser.Absyn;

public class DataType extends Absyn {

  public int type;
  public int size;
  public int p;
  public int s;

  public DataType (int pos, int type, int size, int p, int s) {
    this.pos = pos;
    this.type = type;
    this.size = size;
    this.p = p;
    this.s = s;
  }

  public String print(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("DataType(\n");
    buffer.append("  "+tab+type);
    buffer.append("\n");
    buffer.append("  "+tab+size);
    buffer.append("\n");
    buffer.append("  "+tab+p);
    buffer.append("\n");
    buffer.append("  "+tab+s);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [DataType]");
    return buffer.toString();
  }
}
