// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package Absyn;

public class CreateTableExp extends CreateExp {

  public Symbol.Symbol name;
  public ColumnDefList list;

  public CreateTableExp (int pos, Symbol.Symbol name, ColumnDefList list) {
    this.pos = pos;
    this.name = name;
    this.list = list;
  }

  public String print(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("CreateTableExp(\n");
    buffer.append("  "+tab+name);
    buffer.append("\n");
      if (list != null)
        buffer.append(list.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [CreateTableExp]");
    return buffer.toString();
  }
}
