// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package Absyn;

public class DropExp extends SqlExp {

  public int type;
  public Symbol.Symbol name;

  public DropExp (int pos, int type, Symbol.Symbol name) {
	this.pos = pos;
	this.type = type;
    this.name = name;
  }

  public String print(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("DropExp(\n");
    buffer.append("  "+tab+type);
    buffer.append("\n");
    buffer.append("  "+tab+name);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [DropExp]");
    return buffer.toString();
  }
}
