// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package Absyn;

public class FromTable extends Item {

  public Symbol.Symbol tName;
  public SelectExp selectExp;
  public Symbol.Symbol nName;

  public FromTable (int pos, Symbol.Symbol tName, SelectExp selectExp, Symbol.Symbol nName) {
    this.tName = tName;
    this.selectExp = selectExp;
    this.nName = nName;
    this.pos = pos;
  }

  public String print(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("FromTable(\n");
    buffer.append("  "+tab+tName);
    buffer.append("\n");
      if (selectExp != null)
        buffer.append(selectExp.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append("  "+tab+nName);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [FromTable]");
    return buffer.toString();
  }
}
