// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package Absyn;

public class SelectOp extends SelectExp {

  public boolean selectDist;
  public boolean selectAll;
  public SelectColumnList cList;
  public FromTableList tList;
  public WhereExp whereExp;

  public SelectOp (int pos, boolean selectDist, boolean selectAll, SelectColumnList cList, FromTableList tList, WhereExp whereExp) {
    this.selectDist = selectDist;
    this.selectAll = selectAll;
    this.cList = cList;
    this.tList = tList;
    this.whereExp = whereExp;
    this.pos = pos;
  }

  public String print(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("SelectOp(\n");
    buffer.append("  "+tab+selectDist);
    buffer.append("\n");
    buffer.append("  "+tab+selectAll);
    buffer.append("\n");
      if (cList != null)
        buffer.append(cList.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (tList != null)
        buffer.append(tList.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (whereExp != null)
        buffer.append(whereExp.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [SelectOp]");
    return buffer.toString();
  }
}
