// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package Absyn;

public class WhereCondBinExp extends WhereCondExp {

  public boolean isAnd;
  public WhereCondExp left;
  public WhereCondExp right;

  public WhereCondBinExp (int pos, boolean isAnd, WhereCondExp left, WhereCondExp right) {
    this.isAnd = isAnd;
    this.left = left;
    this.right = right;
    this.pos = pos;
  }

  public String print(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("WhereCondBinExp(\n");
    buffer.append("  "+tab+isNeg);
    buffer.append("\n");
    buffer.append("  "+tab+isAnd);
    buffer.append("\n");
      if (left != null)
        buffer.append(left.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (right != null)
        buffer.append(right.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [WhereCondBinExp]");
    return buffer.toString();
  }
}
