
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jul 08 16:30:44 CST 2011
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FOREIGNKEY = 74;
  public static final int AS = 12;
  public static final int DROPCOLUMN = 27;
  public static final int BOOL = 15;
  public static final int FROM = 33;
  public static final int GT = 63;
  public static final int PRIMARYKEY = 48;
  public static final int GE = 66;
  public static final int ASC = 13;
  public static final int LIKE = 39;
  public static final int COMMA = 72;
  public static final int SUM = 51;
  public static final int NOTNULL = 43;
  public static final int RPAREN = 70;
  public static final int REFERENCES = 75;
  public static final int ALL = 7;
  public static final int LT = 64;
  public static final int INTVALUE = 4;
  public static final int DOUBLE = 26;
  public static final int LPAREN = 69;
  public static final int FALSE = 31;
  public static final int NOT = 42;
  public static final int LE = 67;
  public static final int FLOAT = 32;
  public static final int MIN = 41;
  public static final int EQ = 65;
  public static final int CREATETABLE = 18;
  public static final int SELECT = 49;
  public static final int TRUE = 52;
  public static final int PLUS = 59;
  public static final int DIVIDE = 62;
  public static final int UNION = 53;
  public static final int DELETE = 23;
  public static final int DECIMAL = 21;
  public static final int CHAR = 16;
  public static final int STAR = 61;
  public static final int ADD = 6;
  public static final int MAX = 40;
  public static final int DROPTABLE = 29;
  public static final int DOT = 71;
  public static final int INT = 38;
  public static final int DROPVIEW = 30;
  public static final int AVG = 14;
  public static final int NULL = 44;
  public static final int EOF = 0;
  public static final int WHERE = 58;
  public static final int DEFAULT = 22;
  public static final int COUNT = 20;
  public static final int MINUS = 60;
  public static final int UNIQUE = 54;
  public static final int IN = 36;
  public static final int OR = 46;
  public static final int SET = 50;
  public static final int error = 1;
  public static final int ON = 45;
  public static final int GROUPBY = 34;
  public static final int DESC = 24;
  public static final int ID = 2;
  public static final int STRINGVALUE = 3;
  public static final int CREATEINDEX = 17;
  public static final int CHECK = 73;
  public static final int ALTERCOLUMN = 8;
  public static final int VALUES = 56;
  public static final int ANY = 11;
  public static final int ALTERTABLE = 9;
  public static final int VARCHAR = 57;
  public static final int REALVALUE = 5;
  public static final int UPDATE = 55;
  public static final int NEQ = 68;
  public static final int CREATEVIEW = 19;
  public static final int AND = 10;
  public static final int DROPINDEX = 28;
  public static final int ORDERBY = 47;
  public static final int HAVING = 35;
  public static final int DISTINCT = 25;
  public static final int INSERTINTO = 37;
}

