
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 11 09:20:47 CST 2009
//----------------------------------------------------

package Tiger;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 44;
  public static final int LBRACKET = 24;
  public static final int MULT = 31;
  public static final int GE = 38;
  public static final int SLASH = 32;
  public static final int PERIOD = 28;
  public static final int INTEGER = 43;
  public static final int LPAREN = 22;
  public static final int ARRAY = 2;
  public static final int FOR = 7;
  public static final int MINUS = 30;
  public static final int RPAREN = 23;
  public static final int AND = 39;
  public static final int SEMICOLON = 21;
  public static final int LT = 35;
  public static final int TYPE = 16;
  public static final int NIL = 12;
  public static final int OR = 40;
  public static final int IN = 10;
  public static final int COMMA = 19;
  public static final int PLUS = 29;
  public static final int ASSIGN = 41;
  public static final int IF = 9;
  public static final int ID = 42;
  public static final int LE = 36;
  public static final int OF = 13;
  public static final int EOF = 0;
  public static final int RBRACKET = 25;
  public static final int error = 1;
  public static final int BREAK = 3;
  public static final int EQ = 33;
  public static final int COLON = 20;
  public static final int LBRACE = 26;
  public static final int ELSE = 5;
  public static final int FUNC = 8;
  public static final int TO = 15;
  public static final int WHILE = 18;
  public static final int LET = 11;
  public static final int THEN = 14;
  public static final int RBRACE = 27;
  public static final int END = 6;
  public static final int GT = 37;
  public static final int VAR = 17;
  public static final int DO = 4;
  public static final int NOTEQ = 34;
}

