// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package QueryManager.Parser.Absyn;

public class AlgebraOp extends AlgebraExp {

  public Column column;
  public ValueExp value;
  public AggregateExp aggregateExp;

  public AlgebraOp (int pos, Column column, ValueExp value, AggregateExp aggregateExp) {
    this.pos = pos;
	this.column = column;
    this.value = value;
    this.aggregateExp = aggregateExp;
  }

  public String print(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("AlgebraOp(\n");
      if (column != null)
        buffer.append(column.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (value != null)
        buffer.append(value.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (aggregateExp != null)
        buffer.append(aggregateExp.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [AlgebraOp]");
    return buffer.toString();
  }
}
