// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package QueryManager.Parser.Absyn;

public class CmpOp extends Absyn {

  public int type;
  public Column column;
  public SelectExp selectExp;
  public ValueExp value;

  public CmpOp (int pos, int type, Column column, SelectExp selectExp, ValueExp value) {
    this.pos = pos;
    this.type = type;
    this.column = column;
    this.selectExp = selectExp;
    this.value = value;
  }

  public String print(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("CmpOp(\n");
    buffer.append("  "+tab+type);
    buffer.append("\n");
      if (column != null)
        buffer.append(column.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (selectExp != null)
        buffer.append(selectExp.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (value != null)
        buffer.append(value.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [CmpOp]");
    return buffer.toString();
  }
}
