// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package QueryManager.Parser.Absyn;

public class DropExp extends SqlExp {

  public int type;
  public IdList list;

  public DropExp (int pos, int type, IdList list) {
	this.pos = pos;
	this.type = type;
    this.list= list;
  }

  public String print(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("DropExp(\n");
    buffer.append("  "+tab+type);
    buffer.append("\n");
      if (list != null)
        buffer.append(list.print("  "+tab));
      else
          buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [DropExp]");
    return buffer.toString();
  }
}
