// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package QueryManager.Parser.Absyn;

public class InExp extends WhereCondOp {

  public boolean isIn;
  public Column column;
  public SelectExp selectExp;

  public InExp (int pos, boolean isIn, Column column, SelectExp selectExp) {
    this.isIn = isIn;
    this.column = column;
    this.selectExp = selectExp;
    this.pos = pos;
  }

  public String print(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("InExp(\n");
    buffer.append("  "+tab+isNeg);
    buffer.append("\n");
    buffer.append("  "+tab+isIn);
    buffer.append("\n");
      if (column != null)
        buffer.append(column.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (selectExp != null)
        buffer.append(selectExp.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [InExp]");
    return buffer.toString();
  }
}
