// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package Absyn;

public class InsertExp extends SqlExp {

  public String name;
  public IdList iList;
  public ValueExpList vlist;

  public InsertExp (int pos, String name, IdList iList, ValueExpList vlist) {
    this.name = name;
    this.iList = iList;
    this.vlist = vlist;
    this.pos = pos;
  }

  public String print(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("InsertExp(\n");
    buffer.append("  "+tab+name);
    buffer.append("\n");
      if (iList != null)
        buffer.append(iList.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (vlist != null)
        buffer.append(vlist.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [InsertExp]");
    return buffer.toString();
  }
}
