// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package Absyn;

public class IntExp extends ValueExp {

  public int value;

  public IntExp (int pos, int value) {
    this.value = value;
    this.pos = pos;
  }

  public String print(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("IntExp(\n");
    buffer.append("  "+tab+value);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [IntExp]");
    return buffer.toString();
  }
}
