// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package Absyn;

public class SelectColumnList extends List {

  public SelectColumn head;
  public SelectColumnList tail;

  public SelectColumnList (int pos, SelectColumn head, SelectColumnList tail) {
    this.head = head;
    this.tail = tail;
    this.pos = pos;
  }

  public String print(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("SelectColumnList(\n");
      if (head != null)
        buffer.append(head.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (tail != null)
        buffer.append(tail.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [SelectColumnList]");
    return buffer.toString();
  }
}
