// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package Absyn;

public class AlterExp extends SqlExp {

  public int type;
  public Symbol.Symbol tName;
  public Symbol.Symbol cName;
  public DataType dataType;

  public AlterExp (int pos, int type, Symbol.Symbol tName, Symbol.Symbol cName, DataType dataType) {
    this.pos = pos;
	this.type = type;
    this.tName = tName;
    this.cName = cName;
    this.dataType = dataType;
  }

  public String print(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("AlterExp(\n");
    buffer.append("  "+tab+type);
    buffer.append("\n");
    buffer.append("  "+tab+tName);
    buffer.append("\n");
    buffer.append("  "+tab+cName);
    buffer.append("\n");
      if (dataType != null)
        buffer.append(dataType.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [AlterExp]");
    return buffer.toString();
  }
}
