// The following code was generated by visual classgen 1.0 on 11-7-8 下午4:37

package QueryManager.Parser.Absyn;

public interface Const {

  public final static int PRIMARYKEY = 0;
  public final static int UNIQUE = 1;
  public final static int NOTNULL = 2;
  public final static int NOCONS = 3;
  public final static int INT = 4;
  public final static int FLOAT = 5;
  public final static int DOUBLE = 6;
  public final static int DECIMAL = 7;
  public final static int CHAR = 8;
  public final static int VARCHAR = 9;
  public final static int BOOL = 10;
  public final static int PLUS = 11;
  public final static int MINUS = 12;
  public final static int STAR = 13;
  public final static int DIVIDE = 14;
  public final static int AVG = 15;
  public final static int MAX = 16;
  public final static int MIN = 17;
  public final static int SUM = 18;
  public final static int COUNT = 19;
  public final static int EQ = 20;
  public final static int NEQ = 21;
  public final static int GT = 22;
  public final static int GE = 23;
  public final static int LT = 24;
  public final static int LE = 25;
  public final static int ALL = 26;
  public final static int ANY = 27;
  public final static int SOLO = 28;
  public final static int INDEX = 29;
  public final static int TABLE = 30;
  public final static int VIEW = 31;
  public final static int ADD = 32;
  public final static int ALTER = 33;
  public final static int DROP = 34;

}
