// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package Absyn;

public class DataType extends Absyn {

	public int type;
	public int size;
	public int p;
	public int s;

	public DataType(int pos, String type, String size, String p, String s) {
		this.pos = pos;
		this.type = Integer.valueOf(type);
		this.size = Integer.valueOf(size);
		this.p = Integer.valueOf(p);
		this.s = Integer.valueOf(s);
	}
//
//	public boolean equals(DataType d) {
//		if (type == d.type && size == d.size && p == d.p && s == d.s)
//			return true;
//		else
//			return false;
//	}

	public String print(String tab) {
		StringBuffer buffer = new StringBuffer();
		buffer.append(tab);
		buffer.append("DataType(\n");
		buffer.append("  " + tab + type);
		buffer.append("\n");
		buffer.append("  " + tab + size);
		buffer.append("\n");
		buffer.append("  " + tab + p);
		buffer.append("\n");
		buffer.append("  " + tab + s);
		buffer.append("\n");
		buffer.append(tab);
		buffer.append(") [DataType]");
		return buffer.toString();
	}
}
