// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package Absyn;

public class GroupExp extends Absyn {

  public ColumnList list;
  public HavingExp havingExp;

  public GroupExp (int pos, ColumnList list, HavingExp havingExp) {
    this.list = list;
    this.havingExp = havingExp;
    this.pos = pos;
  }

  public String print(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("GroupExp(\n");
      if (list != null)
        buffer.append(list.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (havingExp != null)
        buffer.append(havingExp.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [GroupExp]");
    return buffer.toString();
  }
}
