// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package Absyn;

public class StrExp extends ValueExp {

	public String value;

	public StrExp(int pos, String value) {
		this.value = value;
		this.pos = pos;
	}

	public String getValue() {
		return value;
	}

	public int getType() {
		return Const.STRINGVALUE;
	}

	public String print(String tab) {
		StringBuffer buffer = new StringBuffer();
		buffer.append(tab);
		buffer.append("StrExp(\n");
		buffer.append("  " + tab + value);
		buffer.append("\n");
		buffer.append(tab);
		buffer.append(") [StrExp]");
		return buffer.toString();
	}
}
