// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package Absyn;

public abstract class ValueExp extends Item {
	public String getValue() {
		return null;
	};
	
	public int getType() {
		return Const.INVALID;
	}
}
