//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Sep 09 16:00:12 CST 2009
//----------------------------------------------------

package parse;

/** CUP generated class containing symbol constants. */
public class sym {
	/* terminals */
	public static final int FOREIGNKEY = 74;
	public static final int AS = 43;
	public static final int TIMES = 19;
	public static final int FROM = 36;
	public static final int GT = 13;
	public static final int TIME = 67;
	public static final int TIMEVAL = 5;
	public static final int PRIMARYKEY = 57;
	public static final int TABLE = 49;
	public static final int ROLLBACK = 80;
	public static final int GE = 15;
	public static final int ASC = 41;
	public static final int LIKE = 28;
	public static final int COMMA = 9;
	public static final int SUM = 72;
	public static final int RBRACE = 24;
	public static final int INTVAL = 6;
	public static final int RPAREN = 22;
	public static final int REFERENCES = 73;
	public static final int ALL = 32;
	public static final int LT = 14;
	public static final int LBRACE = 23;
	public static final int LPAREN = 21;
	public static final int NOT = 25;
	public static final int DATEVAL = 4;
	public static final int VIEW = 76;
	public static final int LE = 16;
	public static final int FLOAT = 62;
	public static final int MIN = 70;
	public static final int EQ = 11;
	public static final int SELECT = 35;
	public static final int ALTER = 47;
	public static final int PLUS = 17;
	public static final int DIVIDE = 20;
	public static final int INDEX = 59;
	public static final int EXISTS = 30;
	public static final int DELETE = 52;
	public static final int CHAR = 63;
	public static final int BOOLEAN = 65;
	public static final int ESCAPE = 29;
	public static final int ADD = 55;
	public static final int MAX = 71;
	public static final int DOT = 10;
	public static final int INT = 61;
	public static final int AVG = 68;
	public static final int NULL = 34;
	public static final int EOF = 0;
	public static final int SEMICOLON = 8;
	public static final int WHERE = 37;
	public static final int DEFAULT = 56;
	public static final int COUNT = 69;
	public static final int MINUS = 18;
	public static final int FLOATVAL = 7;
	public static final int UNIQUE = 58;
	public static final int IN = 31;
	public static final int DATE = 66;
	public static final int OR = 27;
	public static final int SET = 54;
	public static final int error = 1;
	public static final int START = 77;
	public static final int ON = 60;
	public static final int GROUPBY = 38;
	public static final int DESC = 42;
	public static final int ID = 2;
	public static final int CHECK = 75;
	public static final int DATABASE = 48;
	public static final int VALUES = 53;
	public static final int ANY = 33;
	public static final int CREATE = 45;
	public static final int TRANSACTION = 78;
	public static final int VARCHAR = 64;
	public static final int UPDATE = 51;
	public static final int STRING = 3;
	public static final int NEQ = 12;
	public static final int COMMIT = 79;
	public static final int AND = 26;
	public static final int DROP = 46;
	public static final int ORDERBY = 40;
	public static final int HAVING = 39;
	public static final int DISTINCT = 44;
	public static final int INSERTINTO = 50;
}
