/* The following code was generated by JFlex 1.4.3 on 10-12-14 ÏÂÎç11:41 */

package Parse;
import ErrorMsg.ErrorMsg;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 10-12-14 ÏÂÎç11:41 from the specification file
 * <tt>E:/Documents/workspace/Chap2/src/Parse/tiger_1.3.flex</tt>
 */
class Yylex implements Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int INSLASH = 6;
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\56\1\56\1\0\2\57\22\0\1\1\1\0\1\5\3\0"+
    "\1\51\1\0\1\35\1\36\1\7\1\52\1\10\1\33\1\34\1\6"+
    "\12\3\1\11\1\37\1\24\1\23\1\22\2\0\32\2\1\45\1\55"+
    "\1\46\1\0\1\4\1\0\1\27\1\47\1\44\1\20\1\12\1\25"+
    "\1\2\1\41\1\17\1\2\1\50\1\13\1\2\1\16\1\21\1\32"+
    "\1\2\1\26\1\14\1\31\1\43\1\42\1\40\1\2\1\30\1\2"+
    "\1\53\1\15\1\54\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\2\2\1\11\4\2\1\12\1\13\1\14\3\2"+
    "\1\15\1\16\1\17\1\20\1\21\2\2\1\22\1\23"+
    "\1\2\1\24\1\25\1\26\1\27\1\30\1\31\2\32"+
    "\1\33\3\1\1\32\1\34\1\35\1\36\1\37\1\40"+
    "\4\2\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\3\2\1\50\5\2\1\0\1\51\1\52\1\53\1\54"+
    "\1\2\1\55\1\56\1\57\1\60\5\2\1\61\1\2"+
    "\1\0\1\62\2\2\1\63\1\64\2\2\1\65\1\2"+
    "\1\66\1\67\1\70\2\2\1\71";

  private static int [] zzUnpackAction() {
    int [] result = new int[106];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\300\0\360\0\u0120\0\u0150"+
    "\0\u0180\0\u01b0\0\u0150\0\u01e0\0\u0210\0\u0240\0\u0150\0\u0270"+
    "\0\u02a0\0\u02d0\0\u0300\0\u0330\0\u0150\0\u0360\0\u0390\0\u03c0"+
    "\0\u03f0\0\u0150\0\u0150\0\u0150\0\u0150\0\u0150\0\u0420\0\u0450"+
    "\0\u0150\0\u0150\0\u0480\0\u0150\0\u0150\0\u0150\0\u0150\0\u0150"+
    "\0\u04b0\0\u04e0\0\u04b0\0\u0150\0\u0150\0\u0510\0\u0540\0\u0150"+
    "\0\u0150\0\u0150\0\u0150\0\u0150\0\u0150\0\u0570\0\u05a0\0\u05d0"+
    "\0\u0600\0\360\0\360\0\360\0\360\0\u0150\0\u0150\0\u0150"+
    "\0\u0630\0\u0660\0\u0690\0\360\0\u06c0\0\u06f0\0\u0720\0\u0750"+
    "\0\u0780\0\u07b0\0\u0150\0\u0150\0\u0150\0\u0150\0\u07e0\0\360"+
    "\0\360\0\360\0\360\0\u0810\0\u0840\0\u0870\0\u08a0\0\u08d0"+
    "\0\360\0\u0900\0\u0930\0\360\0\u0960\0\u0990\0\360\0\360"+
    "\0\u09c0\0\u09f0\0\u0150\0\u0a20\0\360\0\360\0\360\0\u0a50"+
    "\0\u0a80\0\360";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[106];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\5\1\6\1\7\1\0\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\6\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\6\1\30"+
    "\1\6\1\31\1\6\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\6\1\40\2\6\1\41\1\42\1\43\1\6"+
    "\1\44\1\45\1\46\1\47\1\0\2\5\1\0\1\50"+
    "\3\0\1\51\47\0\1\52\1\53\1\54\6\55\1\56"+
    "\1\57\50\55\1\60\1\5\3\60\1\61\47\60\1\62"+
    "\2\5\1\0\1\5\54\0\2\5\2\0\3\6\5\0"+
    "\3\6\1\0\4\6\3\0\6\6\5\0\5\6\2\0"+
    "\2\6\12\0\1\7\143\0\1\63\56\0\1\64\74\0"+
    "\1\65\36\0\3\6\5\0\1\6\1\66\1\6\1\0"+
    "\1\67\3\6\3\0\6\6\5\0\5\6\2\0\2\6"+
    "\11\0\3\6\5\0\1\70\2\6\1\0\4\6\3\0"+
    "\6\6\5\0\5\6\2\0\2\6\11\0\3\6\5\0"+
    "\3\6\1\0\1\6\1\71\2\6\3\0\6\6\5\0"+
    "\5\6\2\0\2\6\11\0\3\6\5\0\3\6\1\0"+
    "\1\72\3\6\3\0\1\73\5\6\5\0\5\6\2\0"+
    "\2\6\11\0\3\6\5\0\3\6\1\0\3\6\1\74"+
    "\3\0\6\6\5\0\5\6\2\0\2\6\11\0\3\6"+
    "\5\0\3\6\1\0\4\6\3\0\1\75\5\6\5\0"+
    "\5\6\2\0\2\6\32\0\1\76\56\0\1\77\1\100"+
    "\36\0\3\6\5\0\3\6\1\0\3\6\1\101\3\0"+
    "\6\6\5\0\3\6\1\102\1\6\2\0\2\6\11\0"+
    "\3\6\5\0\3\6\1\0\4\6\3\0\1\6\1\103"+
    "\4\6\5\0\5\6\2\0\2\6\11\0\3\6\5\0"+
    "\3\6\1\0\3\6\1\104\3\0\3\6\1\105\2\6"+
    "\5\0\1\6\1\106\3\6\2\0\2\6\11\0\3\6"+
    "\5\0\3\6\1\0\4\6\3\0\6\6\5\0\1\6"+
    "\1\107\3\6\2\0\2\6\11\0\3\6\5\0\3\6"+
    "\1\0\4\6\3\0\2\6\1\110\3\6\5\0\5\6"+
    "\2\0\2\6\11\0\3\6\5\0\3\6\1\0\4\6"+
    "\3\0\1\6\1\111\4\6\5\0\5\6\2\0\2\6"+
    "\14\0\1\53\47\0\2\53\4\0\1\112\1\0\1\53"+
    "\10\0\1\113\12\0\1\114\23\0\2\53\10\0\1\115"+
    "\56\0\1\116\53\0\3\6\5\0\2\6\1\117\1\0"+
    "\4\6\3\0\6\6\5\0\5\6\2\0\2\6\11\0"+
    "\3\6\5\0\3\6\1\0\2\6\1\120\1\6\3\0"+
    "\6\6\5\0\5\6\2\0\2\6\11\0\3\6\5\0"+
    "\3\6\1\0\4\6\3\0\4\6\1\121\1\6\5\0"+
    "\5\6\2\0\2\6\11\0\3\6\5\0\1\6\1\122"+
    "\1\6\1\0\4\6\3\0\6\6\5\0\5\6\2\0"+
    "\2\6\11\0\3\6\5\0\3\6\1\0\4\6\3\0"+
    "\1\6\1\123\4\6\5\0\5\6\2\0\2\6\11\0"+
    "\3\6\5\0\3\6\1\0\1\124\3\6\3\0\6\6"+
    "\5\0\5\6\2\0\2\6\11\0\3\6\5\0\3\6"+
    "\1\0\4\6\3\0\1\6\1\125\4\6\5\0\5\6"+
    "\2\0\2\6\11\0\3\6\5\0\3\6\1\0\4\6"+
    "\3\0\5\6\1\126\5\0\5\6\2\0\2\6\11\0"+
    "\3\6\5\0\1\127\2\6\1\0\4\6\3\0\6\6"+
    "\5\0\5\6\2\0\2\6\11\0\3\6\5\0\3\6"+
    "\1\0\1\6\1\130\2\6\3\0\6\6\5\0\5\6"+
    "\2\0\2\6\11\0\3\6\5\0\3\6\1\0\4\6"+
    "\3\0\1\6\1\131\4\6\5\0\5\6\2\0\2\6"+
    "\11\0\3\6\5\0\1\132\2\6\1\0\4\6\3\0"+
    "\6\6\5\0\5\6\2\0\2\6\12\0\1\133\56\0"+
    "\3\6\5\0\1\134\2\6\1\0\4\6\3\0\6\6"+
    "\5\0\5\6\2\0\2\6\11\0\3\6\5\0\3\6"+
    "\1\0\4\6\3\0\6\6\5\0\4\6\1\135\2\0"+
    "\2\6\11\0\3\6\5\0\3\6\1\0\4\6\3\0"+
    "\2\6\1\136\3\6\5\0\5\6\2\0\2\6\11\0"+
    "\3\6\5\0\1\137\2\6\1\0\4\6\3\0\6\6"+
    "\5\0\5\6\2\0\2\6\11\0\3\6\5\0\3\6"+
    "\1\0\1\140\3\6\3\0\6\6\5\0\5\6\2\0"+
    "\2\6\11\0\3\6\5\0\1\6\1\141\1\6\1\0"+
    "\4\6\3\0\6\6\5\0\5\6\2\0\2\6\11\0"+
    "\3\6\5\0\3\6\1\0\4\6\3\0\2\6\1\142"+
    "\3\6\5\0\5\6\2\0\2\6\12\0\1\143\56\0"+
    "\3\6\5\0\3\6\1\0\4\6\3\0\4\6\1\144"+
    "\1\6\5\0\5\6\2\0\2\6\11\0\3\6\5\0"+
    "\3\6\1\0\4\6\3\0\3\6\1\145\2\6\5\0"+
    "\5\6\2\0\2\6\11\0\3\6\5\0\1\146\2\6"+
    "\1\0\4\6\3\0\6\6\5\0\5\6\2\0\2\6"+
    "\11\0\3\6\5\0\3\6\1\0\4\6\3\0\6\6"+
    "\5\0\5\6\2\0\1\6\1\147\11\0\3\6\5\0"+
    "\3\6\1\0\1\6\1\150\2\6\3\0\6\6\5\0"+
    "\5\6\2\0\2\6\11\0\3\6\5\0\3\6\1\0"+
    "\3\6\1\151\3\0\6\6\5\0\5\6\2\0\2\6"+
    "\11\0\3\6\5\0\3\6\1\0\1\152\3\6\3\0"+
    "\6\6\5\0\5\6\2\0\2\6\7\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2736];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\3\1\1\11\2\1\1\11\3\1\1\11\5\1"+
    "\1\11\4\1\5\11\2\1\2\11\1\1\5\11\3\1"+
    "\2\11\2\1\6\11\10\1\3\11\11\1\1\0\4\11"+
    "\14\1\1\0\7\1\1\11\7\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[106];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
int count;
StringBuffer string =new StringBuffer();
private void newline() {
  errorMsg.newline(yychar);
}

private void err(int pos, String s) {
  errorMsg.error(pos,s);
}

private void err(String s) {
  err(yychar,s);
}

private java_cup.runtime.Symbol tok(int kind, Object value) {
    return new java_cup.runtime.Symbol(kind, yychar, yychar+yylength(), value);
}

private ErrorMsg errorMsg;

Yylex(java.io.InputStream s, ErrorMsg e) {
  this(s);
  errorMsg=e;
}



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 128) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol nextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 25: 
          { yybegin(YYINITIAL); return tok(sym.STRING,string.toString());
          }
        case 58: break;
        case 37: 
          { return tok(sym.GE,null);
          }
        case 59: break;
        case 44: 
          { count--; if (count==0) {yybegin(YYINITIAL);}
          }
        case 60: break;
        case 14: 
          { return tok(sym.DOT,null);
          }
        case 61: break;
        case 15: 
          { return tok(sym.LPAREN,null);
          }
        case 62: break;
        case 23: 
          { return tok(sym.RBRACE,null);
          }
        case 63: break;
        case 8: 
          { return tok(sym.COLON,null);
          }
        case 64: break;
        case 11: 
          { return tok(sym.EQ,null);
          }
        case 65: break;
        case 21: 
          { return tok(sym.PLUS,null);
          }
        case 66: break;
        case 4: 
          { string.setLength(0);yybegin(STRING);
          }
        case 67: break;
        case 27: 
          { err("String error");
          }
        case 68: break;
        case 39: 
          { return tok(sym.LE,null);
          }
        case 69: break;
        case 57: 
          { return tok(sym.FUNCTION,null);
          }
        case 70: break;
        case 53: 
          { int temp=Integer.parseInt(yytext().substring(1,4));
		if(temp>255) err("\\ddd overflow"); 
		else string.append((char)temp);
          }
        case 71: break;
        case 42: 
          { string.append('\t');
          }
        case 72: break;
        case 55: 
          { return tok(sym.WHILE,null);
          }
        case 73: break;
        case 17: 
          { return tok(sym.SEMICOLON,null);
          }
        case 74: break;
        case 56: 
          { return tok(sym.BREAK,null);
          }
        case 75: break;
        case 10: 
          { return tok(sym.GT,null);
          }
        case 76: break;
        case 13: 
          { return tok(sym.MINUS,null);
          }
        case 77: break;
        case 16: 
          { return tok(sym.RPAREN,null);
          }
        case 78: break;
        case 43: 
          { count++;
          }
        case 79: break;
        case 51: 
          { return tok(sym.TYPE,null);
          }
        case 80: break;
        case 50: 
          { return tok(sym.ELSE,null);
          }
        case 81: break;
        case 12: 
          { return tok(sym.LT,null);
          }
        case 82: break;
        case 48: 
          { return tok(sym.FOR,null);
          }
        case 83: break;
        case 40: 
          { return tok(sym.TO,null);
          }
        case 84: break;
        case 18: 
          { return tok(sym.LBRACK,null);
          }
        case 85: break;
        case 30: 
          { count=1;yybegin(COMMENT);
          }
        case 86: break;
        case 9: 
          { return tok(sym.OR,null);
          }
        case 87: break;
        case 7: 
          { return tok(sym.COMMA,null);
          }
        case 88: break;
        case 54: 
          { return tok(sym.ARRAY,null);
          }
        case 89: break;
        case 46: 
          { return tok(sym.LET,null);
          }
        case 90: break;
        case 24: 
          { string.append(' ');
          }
        case 91: break;
        case 36: 
          { return tok(sym.OF,null);
          }
        case 92: break;
        case 35: 
          { return tok(sym.DO,null);
          }
        case 93: break;
        case 19: 
          { return tok(sym.RBRACK,null);
          }
        case 94: break;
        case 33: 
          { return tok(sym.IN,null);
          }
        case 95: break;
        case 45: 
          { return tok(sym.END,null);
          }
        case 96: break;
        case 38: 
          { return tok(sym.NEQ,null);
          }
        case 97: break;
        case 29: 
          { yybegin(STRING);
          }
        case 98: break;
        case 49: 
          { return tok(sym.VAR,null);
          }
        case 99: break;
        case 41: 
          { string.append('\n');
          }
        case 100: break;
        case 26: 
          { string.append(yytext());
          }
        case 101: break;
        case 28: 
          { err("\\ Unmatch");
          }
        case 102: break;
        case 20: 
          { return tok(sym.AND,null);
          }
        case 103: break;
        case 3: 
          { return tok(sym.INT,new Integer(yytext()));
          }
        case 104: break;
        case 52: 
          { return tok(sym.THEN,null);
          }
        case 105: break;
        case 32: 
          { return tok(sym.ASSIGN,null);
          }
        case 106: break;
        case 5: 
          { return tok(sym.DIVIDE,null);
          }
        case 107: break;
        case 22: 
          { return tok(sym.LBRACE,null);
          }
        case 108: break;
        case 31: 
          { err("Comment error");
          }
        case 109: break;
        case 34: 
          { return tok(sym.IF,null);
          }
        case 110: break;
        case 6: 
          { return tok(sym.TIMES,null);
          }
        case 111: break;
        case 47: 
          { return tok(sym.NIL,null);
          }
        case 112: break;
        case 2: 
          { return tok(sym.ID,yytext());
          }
        case 113: break;
        case 1: 
          { 
          }
        case 114: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              { 	{
	 if (yystate()==COMMENT) err("Comment error");
	 if (yystate()==STRING)  err("String error");
	 if (yystate()==INSLASH) err("In slash error");

	 return tok(sym.EOF, null);
        }
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
