// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package Absyn;

public class HavingExp extends Absyn {

  public HavingCondExp cond;

  public HavingExp (int pos, HavingCondExp cond) {
    this.cond = cond;
    this.pos = pos;
  }

  public String print(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("HavingExp(\n");
      if (cond != null)
        buffer.append(cond.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [HavingExp]");
    return buffer.toString();
  }
}
