// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package Absyn;

public class HavingCondOp extends HavingCondExp {

  public int type;
  public AggregateExp aggregateExp;
  public ValueExp value;

  public HavingCondOp (int pos, int type, AggregateExp aggregateExp, ValueExp value) {
    this.type = type;
    this.aggregateExp = aggregateExp;
    this.value = value;
    this.pos = pos;
  }

  public String print(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("HavingCondOp(\n");
    buffer.append("  "+tab+type);
    buffer.append("\n");
      if (aggregateExp != null)
        buffer.append(aggregateExp.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (value != null)
        buffer.append(value.print("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [HavingCondOp]");
    return buffer.toString();
  }
}
