// The following code was generated by visual classgen 1.0 on 11-7-8 上午10:21

package Absyn;

public class NullExp extends ValueExp {

  public NullExp (int pos) {
    this.pos = pos;
  }

  public String print(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("NullExp(\n");
    buffer.append(tab);
    buffer.append(") [NullExp]");
    return buffer.toString();
  }
}
